name = "MaterialPointVisualizer"
uuid = "9ce2fbfb-c269-402f-8683-a675189e795c"
version = "0.3.5"
authors = ["ZenanH <zenan.huo@outlook.com>"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FastPointQuery = "b325ad68-3eea-4afa-b43e-4b8e378fd76d"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
ColorSchemes = "3.31"
DelimitedFiles = "1"
FastPointQuery = "0.5"
GeometryBasics = "0.5"
HDF5 = "0.17"
MeshCat = "1.1"
PrecompileTools = "1.2"
ProgressMeter = "1.10"
Reexport = "1.2"
WriteVTK = "1.21"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]